. $psScriptRoot\count-gdduplicate.ps1
. $psScriptRoot\count-gdshows.ps1
. $psScriptRoot\count-shows2.ps1
. $psScriptRoot\count.ps1
. $psScriptRoot\Find-UnknownCoding.ps1
. $psScriptRoot\Get-GdDuplicatedShow.ps1
. $psScriptRoot\mirrorjerry.ps1
. $psScriptRoot\mirrormusic.ps1
. $psScriptRoot\mirrorshows.ps1
